INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (0, 'None', 'None', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (1, 'Wallet', 'Wallet', 10);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (2, 'Offices', 'OfficeFolder', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (3, 'Wardrobe', 'Wardrobe', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (4, 'Hangar', 'Hangar', 30);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (5, 'Cargo', 'Cargo', 3000);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (6, 'OfficeImpound', 'Impounded Offices', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (7, 'Skill', 'Skill', 15);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (8, 'Reward', 'Reward', 17);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (11, 'LoSlot0', 'Low power slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (12, 'LoSlot1', 'Low power slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (13, 'LoSlot2', 'Low power slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (14, 'LoSlot3', 'Low power slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (15, 'LoSlot4', 'Low power slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (16, 'LoSlot5', 'Low power slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (17, 'LoSlot6', 'Low power slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (18, 'LoSlot7', 'Low power slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (19, 'MedSlot0', 'Medium power slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (20, 'MedSlot1', 'Medium power slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (21, 'MedSlot2', 'Medium power slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (22, 'MedSlot3', 'Medium power slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (23, 'MedSlot4', 'Medium power slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (24, 'MedSlot5', 'Medium power slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (25, 'MedSlot6', 'Medium power slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (26, 'MedSlot7', 'Medium power slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (27, 'HiSlot0', 'High power slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (28, 'HiSlot1', 'High power slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (29, 'HiSlot2', 'High power slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (30, 'HiSlot3', 'High power slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (31, 'HiSlot4', 'High power slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (32, 'HiSlot5', 'High power slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (33, 'HiSlot6', 'High power slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (34, 'HiSlot7', 'High power slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (35, 'Fixed Slot', 'Fixed Slot', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (36, 'AssetSafety', 'Asset Safety', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (56, 'Capsule', 'Capsule', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (57, 'Pilot', 'Pilot', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (61, 'Skill In Training', 'Skill in training', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (62, 'CorpMarket', 'Corporation Market Deliveries / Returns', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (63, 'Locked', 'Locked item, can not be moved unless unlocked', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (64, 'Unlocked', 'Unlocked item, can be moved', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (70, 'Office Slot 1', 'Office slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (71, 'Office Slot 2', 'Office slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (72, 'Office Slot 3', 'Office slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (73, 'Office Slot 4', 'Office slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (74, 'Office Slot 5', 'Office slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (75, 'Office Slot 6', 'Office slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (76, 'Office Slot 7', 'Office slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (77, 'Office Slot 8', 'Office slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (78, 'Office Slot 9', 'Office slot 9', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (79, 'Office Slot 10', 'Office slot 10', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (80, 'Office Slot 11', 'Office slot 11', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (81, 'Office Slot 12', 'Office slot 12', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (82, 'Office Slot 13', 'Office slot 13', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (83, 'Office Slot 14', 'Office slot 14', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (84, 'Office Slot 15', 'Office slot 15', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (85, 'Office Slot 16', 'Office slot 16', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (86, 'Bonus', 'Bonus', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (87, 'DroneBay', 'Drone Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (88, 'Booster', 'Booster', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (89, 'Implant', 'Implant', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (90, 'ShipHangar', 'Ship Hangar', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (91, 'ShipOffline', 'Ship Offline', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (92, 'RigSlot0', 'Rig power slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (93, 'RigSlot1', 'Rig power slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (94, 'RigSlot2', 'Rig power slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (95, 'RigSlot3', 'Rig power slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (96, 'RigSlot4', 'Rig power slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (97, 'RigSlot5', 'Rig power slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (98, 'RigSlot6', 'Rig power slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (99, 'RigSlot7', 'Rig power slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (115, 'CorpSAG1', 'Corp Security Access Group 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (116, 'CorpSAG2', 'Corp Security Access Group 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (117, 'CorpSAG3', 'Corp Security Access Group 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (118, 'CorpSAG4', 'Corp Security Access Group 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (119, 'CorpSAG5', 'Corp Security Access Group 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (120, 'CorpSAG6', 'Corp Security Access Group 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (121, 'CorpSAG7', 'Corp Security Access Group 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (122, 'SecondaryStorage', 'Secondary Storage', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (125, 'SubSystem0', 'Sub system slot 0', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (126, 'SubSystem1', 'Sub system slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (127, 'SubSystem2', 'Sub system slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (128, 'SubSystem3', 'Sub system slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (129, 'SubSystem4', 'Sub system slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (130, 'SubSystem5', 'Sub system slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (131, 'SubSystem6', 'Sub system slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (132, 'SubSystem7', 'Sub system slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (133, 'SpecializedFuelBay', 'Specialized Fuel Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (134, 'SpecializedAsteroidHold', 'Specialized Asteroid Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (135, 'SpecializedGasHold', 'Specialized Gas Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (136, 'SpecializedMineralHold', 'Specialized Mineral Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (137, 'SpecializedSalvageHold', 'Specialized Salvage Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (138, 'SpecializedShipHold', 'Specialized Ship Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (139, 'SpecializedSmallShipHold', 'Specialized Small Ship Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (140, 'SpecializedMediumShipHold', 'Specialized Medium Ship Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (141, 'SpecializedLargeShipHold', 'Specialized Large Ship Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (142, 'SpecializedIndustrialShipHold', 'Specialized Industrial Ship Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (143, 'SpecializedAmmoHold', 'Specialized Ammo Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (144, 'StructureActive', 'Structure Active', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (145, 'StructureInactive', 'Structure Inactive', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (146, 'JunkyardReprocessed', 'This item was put into a junkyard through reprocession.', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (147, 'JunkyardTrashed', 'This item was put into a junkyard through being trashed by its owner.', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (148, 'SpecializedCommandCenterHold', 'Specialized Command Center Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (149, 'SpecializedPlanetaryCommoditiesHold', 'Specialized Planetary Commodities Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (150, 'PlanetSurface', 'Planet Surface', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (151, 'SpecializedMaterialBay', 'Specialized Material Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (152, 'DustCharacterDatabank', 'Dust Character Databank', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (153, 'DustCharacterBattle', 'Dust Character Battle', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (154, 'QuafeBay', 'Quafe Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (155, 'FleetHangar', 'Fleet Hangar', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (156, 'HiddenModifiers', 'Hidden Modifiers', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (157, 'StructureOffline', 'Structure Offline', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (158, 'FighterBay', 'Fighter Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (159, 'FighterTube0', 'Fighter Tube 0', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (160, 'FighterTube1', 'Fighter Tube 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (161, 'FighterTube2', 'Fighter Tube 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (162, 'FighterTube3', 'Fighter Tube 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (163, 'FighterTube4', 'Fighter Tube 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (164, 'StructureServiceSlot0', 'Structure service slot 1', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (165, 'StructureServiceSlot1', 'Structure service slot 2', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (166, 'StructureServiceSlot2', 'Structure service slot 3', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (167, 'StructureServiceSlot3', 'Structure service slot 4', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (168, 'StructureServiceSlot4', 'Structure service slot 5', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (169, 'StructureServiceSlot5', 'Structure service slot 6', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (170, 'StructureServiceSlot6', 'Structure service slot 7', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (171, 'StructureServiceSlot7', 'Structure service slot 8', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (172, 'StructureFuel', 'Structure Fuel', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (173, 'Deliveries', 'Deliveries', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (174, 'CrateLoot', 'Crate Loot', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (176, 'BoosterBay', 'Booster Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (177, 'SubsystemBay', 'Subsystem Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (178, 'Raffles', 'Raffles Hangar', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (179, 'FrigateEscapeBay', 'Frigate escape bay Hangar', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (180, 'StructureDeedBay', 'Structure Deed Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (181, 'SpecializedIceHold', 'Specialized Ice Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (182, 'SpecializedAsteroidHold', 'Specialized Asteroid Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (183, 'MobileDepot', 'Mobile Depot', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (184, 'CorpProjectsHangar', 'Corporation Projects Hangar ', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (185, 'ColonyResourcesHold', 'Infrastructure Hold', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (186, 'MoonMaterialBay', 'Moon Material Bay', 0);
INSERT INTO invFlags (flagID, flagName, flagText, orderID) VALUES (187, 'CapsuleerDeliveries', 'Capsuleer Deliveries', 0);
